local_backend: true

backend:
  name: git-gateway
  branch: master

media_folder: /static/cms-assets
public_folder: /cms/cms-assets

x-patterns:
  html_id: &html_id ['^[a-zA-Z][\w:.\-]*$', 'Must be a valid HTML element ID']

x-fields:
  title: &title
    name: title
    label: Title
    widget: string
  title_slug: &title_slug
    name: slug
    label: ID (Read-Only)
    widget: readonly
    default: "__unset__"
    hint: "Permanent ID used for linking to this resource. Generated once after saving (cannot be changed)."
  icon: &icon
    name: iconName
    label: FontAwesome Icon Name
    widget: string
    hint: 'ex: "rocket", not "fa-rocket"'
  feature: &feature
    name: feature
    label: "Related Feature"
    widget: "select"
    required: false
    hint: (Only display this content for users with access to the selected feature.)
    options:
      - { label: "Access QA Environment", value: "qa_mode" }
      - { label: "Adequacy", value: "adequacy" }
      - { label: "Assess Markets", value: "assess_markets" }
      - { label: "Cms Provider Lookup", value: "cms_provider_lookup" }
      - { label: "Compare Networks", value: "compare_networks" }
      - { label: "Competitive Access", value: "competitive_access" }
      - { label: "Competitive Dashboard", value: "competitive_dashboard" }
      - { label: "Confidence Scores", value: "confidence_scores" }
      - { label: "Cost Impact", value: "cost_impact" }
      - { label: "Create A Directory", value: "create_a_directory" }
      - { label: "Create A List", value: "create_a_list" }
      - { label: "Custom Reports", value: "insights_dashboard" }
      - { label: "Dashboard", value: "dashboard" }
      - { label: "Display Top Hospitals", value: "display_top_hospitals" }
      - { label: "Dropdown Shortcuts", value: "dropdown_shortcuts" }
      - { label: "Export Content", value: "export_content" }
      - { label: "Export Detail", value: "export_detail" }
      - { label: "Export User List", value: "export_user_list" }
      - { label: "Find A Provider", value: "find_a_provider" }
      - { label: "Hds Provider Lookup", value: "hds_provider_lookup" }
      - { label: "Manage Clients", value: "manage_clients" }
      - { label: "Manage Release Notes", value: "manage_release_notes" }
      - { label: "Manage User Defined Clients", value: "manage_user_defined_clients" }
      - { label: "Manage Users", value: "manage_users" }
      - { label: "Md Insider Dialog", value: "md_insider_dialog" }
      - { label: "Measure Disruption", value: "measure_disruption" }
      - { label: "Model Networks", value: "model_networks" }
      - { label: "Provider Client Ids", value: "provider_client_ids" }
      - { label: "Provider Comments", value: "provider_comments" }
      - { label: "Rank Network Drugs", value: "rank_network_drugs" }
      - { label: "Rank Networks", value: "rank_networks" }
      - { label: "Rate Analytics", value: "healthcare_intelligence" }
      - { label: "Recruitment", value: "recruitment" }
      - { label: "Settings", value: "settings" }
      - { label: "Simplified Network Columns", value: "simplified_network_columns" }
      - { label: "Specialty Mappings", value: "specialty_mappings" }
      - { label: "Tags", value: "tags" }
      - { label: "TrueDisruption", value: "true_disruption" }
      - { label: "View Legacy Site", value: "view_legacy_site" }

  tiles: &tiles
    name: tiles
    label: Tiles
    label_singular: Tile
    widget: list
    default: []
    summary: "{{fields.title}}"
    fields:
      - *title
      - name: linkPath
        label: Link Path
        widget: string
        required: false
        hint: "Path to link to when the title is clicked."
      - *icon
      - name: body
        label: Body
        widget: markdown
        required: false

collections:
  - name: config
    label: Config
    files:
      - label: Help Center Navigation
        name: navSidebar
        file: "content/config/navSidebar/data.json"
        fields:
          - name: sections
            label: Sections
            label_singular: Section
            widget: list
            default: []
            collapsed: false
            summary: '{{fields.slug}}'
            fields:
              - *icon
              - name: slug
                label: Section
                widget: relation
                collection: helpSections
                value_field: "slug"
                search_fields: ['title']
                display_fields: ['slug']
              - name: subsections
                label: Subsections
                label_singular: Subsection
                widget: list
                default: []
                summary: "{{fields.slug}}"
                fields:
                  - name: slug
                    label: Subsection
                    widget: relation
                    collection: helpSubsections
                    value_field: "slug"
                    search_fields: ['title']
                    display_fields: ["{{sectionSlug}} / {{fields.slug}}"]

  - name: pages
    label: Pages
    files:
      - label: Help Center Home
        name: home
        file: "content/pages/home/data.json"
        media_folder: "{{media_folder}}/home"
        public_folder: "{{public_folder}}/home"
        fields:
          - *tiles
      - label: Help Center Glossary
        name: helpGlossary
        file: "content/pages/helpGlossary/data.json"
        media_folder: "{{media_folder}}/helpGlossary"
        public_folder: "{{public_folder}}/helpGlossary"
        fields:
          - name: entries
            widget: list
            default: []
            summary: "{{fields.term}}"
            fields:
              - name: term
                label: Term
                widget: string
              - name: description
                label: Description
                widget: markdown
              - *feature
  - name: helpSections
    label: Help Center Sections
    label_singular: Help Center Section
    folder: content/helpSections
    create: true
    path: "{{slug}}"
    extension: json
    media_folder: "{{media_folder}}/helpSections/{{slug}}"
    public_folder: "{{public_folder}}/helpSections/{{slug}}"
    fields:
      - *title
      - *title_slug
      - name: body
        label: Body
        widget: markdown
        required: false
      - *tiles

  - &helpSubsections
    name: helpSubsections
    label: Help Center Subsections
    label_singular: Help Center Subsection
    folder: content/helpSubsections
    create: true
    path: "{{slug}}"
    extension: json
    media_folder: "{{media_folder}}/helpSubsections/{{slug}}"
    public_folder: "{{public_folder}}/helpSubsections/{{slug}}"
    summary: "{{sectionSlug}} / {{title}}"
    sortable_fields: ['sectionSlug', 'title']
    fields:
      - name: sectionSlug
        label: Section
        widget: relation
        collection: helpSections
        value_field: "slug"
        search_fields: ['title']
        display_fields: ['title']
        hint: "The section this subsection belongs to."
      - *title
      - *title_slug
      - name: body
        label: Body
        widget: markdown
        required: false
      - *tiles

  - <<: *helpSubsections
    name: helpFaqSections
    label: Help Center FAQ Sections
    label_singular: Help Center FAQ Section
    filter: { field: sectionSlug, value: faq }

  - name: helpFaqs
    label: Help Center FAQs
    label_singular: Help Center FAQ
    folder: content/helpFaqs
    create: true
    path: "{{slug}}"
    extension: json
    media_folder: "{{media_folder}}/helpFaqs/{{slug}}"
    public_folder: "{{public_folder}}/helpFaqs/{{slug}}"
    summary: "{{sectionSlug}} / {{title}}"
    fields:
      - name: sectionSlug
        label: FAQ Section
        widget: relation
        collection: helpFaqSections
        value_field: "slug"
        search_fields: ['title']
        display_fields: ['title']
      - *feature
      - *title
      - *title_slug
      - name: body
        label: Body
        widget: markdown
        required: false
      - name: entries
        widget: list
        default: []
        summary: "{{fields.question}}"
        fields:
          - name: question
            label: Question
            widget: string
          - name: answer
            label: Answer
            widget: markdown
          - *feature

  - name: legacyHelpSections
    label: Legacy Help Sections
    label_singular: Legacy Help Section
    folder: content/legacyHelp
    create: true
    path: "{{slug}}"
    extension: json
    editor:
      preview: false
    sortable_fields: ['title', 'order']
    media_folder: "{{media_folder}}/legacyHelp/{{slug}}"
    public_folder: "{{public_folder}}/legacyHelp/{{slug}}"
    fields:
      - name: title
        label: Title
        widget: string
      - name: sectionId
        label: ID
        widget: string
        pattern: *html_id
        hint: "Used to link to this section from other sections. WARNING: Changing this ID will break any existing links to this section."
      - name: order
        label: Order
        widget: number
        hint: "Used to list sections in order (lower numbers come first)."
      - name: placeholderId
        label: Placeholder ID
        widget: string
        pattern: *html_id
        hint: "If filled in, this help section will be replaced by content managed by the app. All remaining fields will be ignored."
        required: false
      - name: body
        label: Body
        widget: markdown
        required: false
      - *feature
      - name: faq
        label: FAQ
        widget: object
        fields:
          - name: sections
            widget: list
            default: []
            label_singular: section
            fields:
              - name: title
                label: "Title"
                widget: string
                required: false
              - name: description
                label: "Description"
                widget: string
                required: false
              - name: entries
                widget: list
                default: []
                summary: "{{fields.question}}"
                fields:
                  - name: question
                    label: "Question"
                    widget: string
                    hint: 'ex: "How do I edit my profile picture?"'
                  - name: answer
                    label: "Answer"
                    widget: markdown
                  - *feature
      - name: videos
        label: "Videos"
        widget: list
        default: []
        summary: "{{fields.title}}"
        fields:
          - name: title
            label: "Title"
            widget: string
          - name: description
            label: "Description"
            widget: string
          - name: fileName
            label: "File Name"
            widget: string
          - name: thumbnail
            label: "Thumbnail Image"
            widget: image
          - name: thumbnailAltText
            label: "Thumbnail Alt Text"
            widget: string
