backend:
  name: git-gateway
  branch: production

publish_mode: editorial_workflow

media_folder: /static/cms-assets/media
public_folder: /cms/cms-assets/media

x-patterns:
  html_id: &html_id ['^[a-zA-Z][\w:.\-]*$', "Must be a valid HTML element ID"]
  non_empty: &non_empty ['\S', "Must not be empty"]

x-fields:
  title: &title
    name: title
    label: Title
    widget: string
    pattern: *non_empty
  resource_title: &resource_title
    <<: *title
    pattern:
      [
        '^(?=\s*\S)[\s\S]{1,120}$',
        "Must not be empty, and must not be longer than 120 characters",
      ]
  body: &body
    name: body
    label: Body
    widget: markdown
    required: false
  icon: &icon
    name: iconName
    label: FontAwesome Icon Name
    widget: string
    hint: 'ex: "rocket", not "fa-rocket"'
    pattern: *non_empty
  section: &section
    name: sectionSlug
    label: Section
    widget: relation
    collection: helpSections
    value_field: "{{slug}}"
    search_fields: ["title"]
    display_fields: ["title", "({{slug}})"]
  sub_section: &sub_section
    name: subsectionSlug
    label: Subsection
    widget: relation
    hint: "The subsection this resource should be located under."
    collection: helpSubsections
    value_field: "{{slug}}"
    search_fields: ["title"]
    display_fields: ["{{title}} ({{sectionSlug}}/{{slug}})"]
  feature: &feature
    name: feature
    label: "Viewing Restriction"
    widget: "select"
    required: false
    hint: (Only display this content for users with access to the selected feature.)
    options:
      - { label: "Administrator", value: "role:client_admin" }
      - { label: "Access QA Environment", value: "qa_mode" }
      - { label: "Accessibility", value: "competitive_access" }
      - { label: "Adequacy", value: "adequacy" }
      - { label: "Assess Markets", value: "assess_markets" }
      - { label: "CMS Provider Lookup", value: "cms_provider_lookup" }
      - { label: "Compare Networks", value: "compare_networks" }
      - { label: "Competitive Dashboard", value: "competitive_dashboard" }
      - { label: "Confidence Scores", value: "confidence_scores" }
      - { label: "Cost Impact", value: "cost_impact" }
      - { label: "Create A Directory", value: "create_a_directory" }
      - { label: "Create A List", value: "create_a_list" }
      - { label: "Custom Reports", value: "insights_dashboard" }
      - { label: "Display Top Hospitals", value: "display_top_hospitals" }
      - { label: "Dropdown Shortcuts", value: "dropdown_shortcuts" }
      - { label: "Export Content", value: "export_content" }
      - { label: "Export Detail", value: "export_detail" }
      - { label: "Find A Provider", value: "find_a_provider" }
      - { label: "Manage Users", value: "manage_users" }
      - { label: "Md Insider Dialog", value: "md_insider_dialog" }
      - { label: "Measure Disruption", value: "measure_disruption" }
      - { label: "Model Networks", value: "role:network_modeler" }
      - { label: "Provider Client Ids", value: "provider_client_ids" }
      - { label: "Provider Comments", value: "provider_comments" }
      - { label: "Rank Network Drugs", value: "rank_network_drugs" }
      - { label: "Rank Networks", value: "rank_networks" }
      - { label: "Rate Analytics", value: "healthcare_intelligence" }
      - { label: "Recruitment", value: "recruitment" }
      - { label: "Settings", value: "settings" }
      - {
          label: "Simplified Network Columns",
          value: "simplified_network_columns",
        }
      - { label: "Specialty Mappings", value: "specialty_mappings" }
      - { label: "Tags", value: "tags" }
      - { label: "TrueDisruption", value: "true_disruption" }
      - { label: "View Legacy Site", value: "view_legacy_site" }
  short_description: &short_description
    name: shortDescription
    label: Short Description
    widget: text
    required: false
    hint: "A brief description of the resource (only displays on the search results page)."
  tiles: &tiles
    name: tiles
    label: Tiles
    label_singular: Tile
    widget: list
    default: []
    summary: "{{fields.title}}"
    fields:
      - *icon
      - *title
      - name: linkPath
        label: Link Path
        widget: string
        required: false
        hint: "Path to link to when the title is clicked."
      - *body
  tags: &tags
    name: tagSlugs
    label: Tags
    widget: relation
    multiple: true
    default: []
    collection: tags
    value_field: "{{slug}}"
    search_fields: ["title", "typeSlug"]
    display_fields: ["{{typeSlug}}: {{title}}"]
    required: false

collections:
  - name: config
    label: Config
    files:
      - label: Help Center Navigation
        name: navSidebar
        file: "content/config/navSidebar/data.json"
        editor:
          preview: false
        fields:
          - name: sections
            label: Sections
            label_singular: Section
            widget: list
            default: []
            collapsed: false
            summary: "{{fields.slug}}"
            fields:
              - *icon
              - <<: *section
                name: slug
              - name: subsections
                label: Subsections
                label_singular: Subsection
                widget: list
                default: []
                summary: "{{fields.slug}}"
                fields:
                  - name: slug
                    label: Subsection
                    widget: relation
                    collection: helpSubsections
                    value_field: "{{slug}}"
                    search_fields: ["title"]
                    display_fields: ["{{sectionSlug}} / {{slug}}"]
      - label: Help Center
        name: helpCenter
        file: "config/helpCenter.json"
        editor:
          preview: false
        fields:
          - name: releaseNotesMonthsVisible
            label: Release Notes Visibility (Months)
            widget: number
            default: 24
            value_type: int
            min: 1
            max: 1000
            hint: How many months worth of Release Notes to display within the Help Center.

  - name: pages
    label: Pages
    files:
      - label: Help Center Home
        name: home
        file: "content/pages/home/data.json"
        fields:
          - *tiles
      - label: Help Center Search Hints
        name: helpSearchHints
        file: "content/pages/helpSearchHints/data.json"
        fields:
          - *tiles
      - label: Help Center Glossary
        name: helpGlossary
        file: "content/pages/helpGlossary/data.json"
        fields:
          - name: entries
            widget: list
            default: []
            summary: "{{fields.term}}"
            fields:
              - name: term
                label: Term
                widget: string
                pattern: *non_empty
              - name: description
                label: Description
                widget: markdown
                pattern: *non_empty
              - *feature
              - *tags
              - *short_description

  - name: helpSections
    label: Help Center Sections
    label_singular: Section
    folder: content/helpSections
    create: true
    extension: json
    fields:
      - *resource_title
      - *feature
      - *tags
      - *short_description
      - *body
      - *tiles

  - &helpSubsections
    name: helpSubsections
    label: Help Center Subsections
    label_singular: Subsection
    folder: content/helpSubsections
    create: true
    extension: json
    summary: "{{sectionSlug}} / {{title}}"
    sortable_fields: ["sectionSlug", "title"]
    fields:
      - *section
      - *resource_title
      - *feature
      - *tags
      - *short_description
      - *body
      - *tiles

  - <<: *helpSubsections
    name: helpFaqSections
    label: Help Center FAQ Sections
    label_singular: FAQ Section
    filter: { field: sectionSlug, value: faq }

  - name: helpFaqs
    label: Help Center FAQs
    label_singular: FAQ
    folder: content/helpFaqs
    create: true
    extension: json
    summary: "{{sectionSlug}} / {{title}}"
    fields:
      - <<: *section
        collection: helpFaqSections
      - *resource_title
      - *feature
      - *short_description
      - *body
      - name: entries
        widget: list
        default: []
        summary: "{{fields.question}}"
        fields:
          - name: question
            label: Question
            widget: string
            pattern: *non_empty
          - name: answer
            label: Answer
            widget: markdown
            pattern: *non_empty
          - *feature
          - *tags
          - *short_description

  - name: helpVideos
    label: Help Center Videos
    label_singular: Video
    folder: content/helpVideos
    create: true
    extension: json
    media_folder: "{{media_folder}}"
    public_folder: "{{public_folder}}"
    fields:
      - <<: *section
        required: false
        hint: The section (if any) this video should be shown under when reached from search results.
      - <<: *sub_section
        required: false
        hint: The subsection (if any) this video should be shown under when reached from search results. (If set, the "section" field is ignored.)
      - *resource_title
      - *feature
      - *tags
      - *short_description
      - <<: *body
        name: description
        label: Full Description
        hint: Full description to display on the video's page.
      - name: url
        label: URL
        widget: string
        hint: The full URL of the hosted video file.
        pattern: *non_empty
      - name: duration
        label: Duration
        widget: object
        hint: The length of the video in minutes and seconds. Displays in search results.
        fields:
          - name: mm
            label: Minutes
            widget: number
            value_type: int
            default: null
            min: 0
            max: 1440
          - name: ss
            label: Seconds
            widget: number
            value_type: int
            default: null
            min: 0
            max: 59
      - name: thumbnail
        label: Thumbnail
        hint: Preview image displayed in search results and elsewhere.
        widget: image
        media_folder: "{{media_folder}}/thumbnails"
        public_folder: "{{public_folder}}/thumbnails"
        media_library:
          config:
            max_file_size: 500000

  - name: helpVideoCollections
    label: Help Center Video Collections
    label_singular: Collection
    folder: content/helpVideoCollections
    create: true
    extension: json
    editor:
      preview: false
    fields:
      - *resource_title
      - name: videos
        label: Videos
        label_singular: Video
        widget: list
        default: []
        collapsed: false
        summary: "{{fields.slug}}"
        fields:
          - name: slug
            label: Video
            widget: relation
            collection: helpVideos
            value_field: "{{slug}}"
            search_fields: ["title"]
            display_fields: ["title"]

  - name: helpArticles
    label: Help Center Articles
    label_singular: Article
    folder: content/helpArticles
    create: true
    extension: json
    fields:
      - <<: *section
        required: false
        hint: The section (if any) this article should be shown under when reached from search results.
      - <<: *sub_section
        required: false
        hint: The subsection (if any) this article should be shown under when reached from search results. (If set, the "section" field is ignored.)
      - *resource_title
      - *feature
      - *tags
      - *short_description
      - <<: *body
        required: true

  - name: releaseNotes
    label: Network360 Release Notes
    label_singular: Release Notes
    folder: content/releaseNotes
    create: true
    extension: json
    summary: "{{releaseDate}}"
    sortable_fields: ["releaseDate"]
    identifier_field: releaseDate
    fields:
      - name: releaseDate
        label: Release Date
        required: true
        widget: datetime
        picker_utc: true
        format: "YYYY-MM-DD"
        time_format: ""
        default: ""
      - <<: *short_description
        hint: A brief overview of the release (displays in search results).
        required: true
      - <<: *body
        required: true

  - name: tagTypes
    label: Tag Types
    label_singular: Type
    folder: content/tagTypes
    create: true
    extension: json
    editor:
      preview: false
    fields:
      - *resource_title
      - name: order
        label: Order
        widget: number
        min: 0
        max: 1000
        hint: "Decides placement of tag type in the filter list (lower numbers come first)."

  - name: tags
    label: Tags
    label_singular: Tag
    folder: content/tags
    create: true
    extension: json
    summary: "{{title}} ({{typeSlug}})"
    sortable_fields: ["title"]
    editor:
      preview: false
    view_groups:
      - label: Type
        field: typeSlug
    fields:
      - name: typeSlug
        label: Type
        widget: relation
        collection: tagTypes
        value_field: "{{slug}}"
        search_fields: ["title"]
        display_fields: ["title"]
      - *resource_title

  - name: legacyHelpSections
    label: Legacy Help Sections
    label_singular: Section
    folder: content/legacyHelp
    create: false
    extension: json
    editor:
      preview: false
    sortable_fields: ["title", "order"]
    fields:
      - name: title
        label: Title
        widget: string
      - name: sectionId
        label: ID
        widget: string
        pattern: *html_id
        hint: "Used to link to this section from other sections. WARNING: Changing this ID will break any existing links to this section."
      - name: order
        label: Order
        widget: number
        hint: "Used to list sections in order (lower numbers come first)."
      - name: placeholderId
        label: Placeholder ID
        widget: string
        pattern: *html_id
        hint: "If filled in, this help section will be replaced by content managed by the app. All remaining fields will be ignored."
        required: false
      - *body
      - *feature
      - name: faq
        label: FAQ
        widget: object
        fields:
          - name: sections
            widget: list
            default: []
            label_singular: section
            fields:
              - name: title
                label: "Title"
                widget: string
                required: false
              - name: description
                label: "Description"
                widget: string
                required: false
              - name: entries
                widget: list
                default: []
                summary: "{{fields.question}}"
                fields:
                  - name: question
                    label: "Question"
                    widget: string
                    hint: 'ex: "How do I edit my profile picture?"'
                  - name: answer
                    label: "Answer"
                    widget: markdown
                  - *feature
      - name: videos
        label: "Videos"
        widget: list
        default: []
        summary: "{{fields.title}}"
        fields:
          - name: title
            label: "Title"
            widget: string
          - name: description
            label: "Description"
            widget: string
          - name: fileName
            label: "File Name"
            widget: string
          - name: thumbnail
            label: "Thumbnail Image"
            widget: image
          - name: thumbnailAltText
            label: "Thumbnail Alt Text"
            widget: string
